### PR TITLE
Update to work with Ubuntu 20.04 and ROS2 Foxy.

### PR DESCRIPTION
**Pull request by tdenewiler**

### CODE REVIEW

**Comment by jpliquid** [comment]
Hi @tdenewiler 

Thank you for your PR about Foxy and Gazebo 11. At first glance, your changes to use Gazebo 11 match what I had noted before. I need some time to review it more deeply.

**Comment by jpliquid** [comment]
@tdenewiler I could review your PR and I approve your changes.

However, some features are missing to finalize a migration to Foxy.

- [ ]  `node-name` in the XML launch files and `node_name` in the python ones are deprecated and should be renamed to `name`

- [ ]  `node_executable` in the python launch files is deprecated and should be renamed to `executable`

- [ ]  `node_namespace` in the python launch files is deprecated and should be renamed to `namespace`

- [ ]  CMake macro `ament_export_interfaces` is deprecated and should be renamed to `ament_export_targets` 

- [ ] Xacro now benefits from a better support and allows a direct parsing of xacro files to a given parameter instead of writing the resulting file in the disk. Implied changes: 

- uuv_descriptions, uuv_thruster_manager/tests, uuv_gazebo_ros_plugins python launch files where the generation of the parsed file is replaced by a string parameter `robot_description` passed to the node constructor. The string could be obtained either by a launch.substitions.Command call or a xacro.process() call.

- thruster_manager.py could read a robot_description parameter instead of loading the file to get information from the urdf description. Parameters are no longer global as they were in ROS 1, so a new way to do it has yet to be choosen (read the parameter stored in which node ?).

Pending:
- [ ] Force system gazebo plugin should be loaded by default when launching Gazebo server ([see here](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/7bf18c7ad727e0d5f3c80c4dee01fc1429c16093/gazebo_ros/launch/gzserver.launch.py#L53)). However, installing Gazebo ros pkgs from `sudo apt install ros-foxy-gazebo-ros-pkgs` is not sync with the foxy branch of their repository and force system is still not loaded by default. So, I'm just writing it for information.

I have two questions:
Have you checked the checkbox allowing maintainers to push to your pull request ? If not, would you mind allowing us to push ?
Let me know if you are willing to to do some tasks (xacro part is clearly the most time consuming). Otherwise, I can do it myself, there are no problems.

**Comment by tdenewiler** [comment]
@jpliquid, in my view of the PR I can see the box checked next to `Allow edits by maintainers`. You should be good to go there.

I am happy to work on some of the items in your list, which is a nice list by the way. Was that list posted somewhere before now? Do you have a recommended way of testing, and what you look for while doing it? I was using Github Actions and running the launch files from your [`Test the package`](https://github.com/Liquid-ai/Plankton#5-test-the-package) section. The launch files would get hung up on spawning a new vehicle.

Another question I have is whether you intend to continue supporting ROS2 Eloquent? There are some changes to `CMakeLists.txt` that are recommended when moving to Foxy, but I didn't want to include those if you are still trying to support older versions of ROS2. Your list seems to include things that might break Eloquent support.

I don't have a lot of free time this week, but I think most of the desired changes in your list are straightforward. Whether I could finish it this week partly depends on how much backwards compatibility you want to keep :)

**Comment by jpliquid** [comment]
@tdenewiler, My list was not posted anywhere, I've just summarized and collected what I know is needed for the migration these last few days.

I don't really have a recommended way to test and I find that testing the whole package can be really time consuming. As you said, a nice start is the test example in the readme and the unit tests (with `colcon test --packages-up-to plankton`, which is also equivalent to our Github Action). 
In general, I try to test each package independently for each file. I have also tested other vehicles like [eca_a9](https://github.com/uuvsimulator/eca_a9). There are many example files in uuv_gazebo and uuv_tutorials, but I haven't migrated them yet.
In my opinion, a not-so-bad and quick way to globally proceed is to compare the behaviour of the simulation in Plankton with UUV Simulator, either visually or using for example tools like `rqt_gui` to check that the connections of topics and nodes are the same.

The plan is indeed to move to Foxy and drop Eloquent support, except maybe for critical patches. Actually, I have already created a new branch `eloquent` and your pull request will be merged to the master branch, which will reflect Foxy. So, you are very welcome to share what could be the changes related to `CMakelist.txt` :)
Next step will be to update the installation instructions in the readme / changelog / version / Github actions.

If you are happy to work on some items in my list, I appreciate your help! I could do the xacro related part and leave you the rest of the tasks for example if it suits you. They are straightforward as you noticed, but implies _many many_ files to change (almost all the launch files, some CMake)

>  The launch files would get hung up on spawning a new vehicle.

 What do you mean ? Is it an issue when spawning a second vehicle ?

**Comment by tdenewiler** [comment]
@jpliquid, here is what I mean by the launch files get hung up. This could be related to the xacro issues you are already aware of.

In Terminal 1 I run the following, and see Gazebo start up. It looks the same as UUV Simulator.

```shell
ros2 launch uuv_gazebo_worlds ocean_waves.launch
```

In Terminal 2 I run

```shell
ros2 launch uuv_descriptions upload_rexrov.launch mode:=default x:=0 y:=0 z:=-20 namespace:=rexrov
```

The last of Terminal 2 output is

```shell
[spawn_entity.py-1] [INFO] [1607013819.435319489] - rexrov.urdf_spawner:/opt/ros/foxy/lib/gazebo_ros/spawn_entity.py:_spawn_entity:282: Spawn status: SpawnEntity: Successfully spawned entity [rexrov]
```

But an issue occurs in Terminal 1 after I run the launch command in Terminal 2. I get the following error message, and no vehicle shows up in Gazebo.

```shell
[gzserver-2] Error [parser_urdf.cc:3193] Unable to call parseURDF on robot model
[gzserver-2] Error [parser.cc:488] parse as old deprecated model file failed.
```

**Comment by tdenewiler** [comment]
FYI, I used `find . -name \*.launch | xargs grep node-name` to find all instances that needed to be changed in the launch files (and similar commands for the other strings to change).

**Comment by jpliquid** [comment]
Ok, I see. I have the same message and the error comes from [the parser here](https://github.com/osrf/sdformat/blob/983e8fae73ace20897c97dffacbd00fb0ec01ccc/src/parser_urdf.cc#L3219). But that's weird that no vehicle shows up. In my case, the error seems transparent and I see the vehicle (Eloquent & Foxy) in Gazebo and rviz. I need to take some time to investigate anyway.

Thanks for the first updates by the way.

**Comment by theaimer09** [comment]
> @jpliquid, here is what I mean by the launch files get hung up. This could be related to the xacro issues you are already aware of.
> 
> In Terminal 1 I run the following, and see Gazebo start up. It looks the same as UUV Simulator.
> 
> ```shell
> ros2 launch uuv_gazebo_worlds ocean_waves.launch
> ```
> 
> In Terminal 2 I run
> 
> ```shell
> ros2 launch uuv_descriptions upload_rexrov.launch mode:=default x:=0 y:=0 z:=-20 namespace:=rexrov
> ```
> 
> The last of Terminal 2 output is
> 
> ```shell
> [spawn_entity.py-1] [INFO] [1607013819.435319489] - rexrov.urdf_spawner:/opt/ros/foxy/lib/gazebo_ros/spawn_entity.py:_spawn_entity:282: Spawn status: SpawnEntity: Successfully spawned entity [rexrov]
> ```
> 
> But an issue occurs in Terminal 1 after I run the launch command in Terminal 2. I get the following error message, and no vehicle shows up in Gazebo.
> 
> ```shell
> [gzserver-2] Error [parser_urdf.cc:3193] Unable to call parseURDF on robot model
> [gzserver-2] Error [parser.cc:488] parse as old deprecated model file failed.
> ```

Hi, I got this question too, I don't know how it happened, have you solved it?

**Pull request merged**
